spring.application.name=order-service
server.port=8086
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/auth_db
spring.datasource.username=root
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
eureka.client.service-url.defaultZone=http://localhost:8080/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
# Logging configuration for Orders microservice
logging.level.com.cropdeal.orders=INFO
logging.level.com.cropdeal.orders.resources=DEBUG
logging.level.com.cropdeal.orders.services=DEBUG
logging.level.com.cropdeal.orders.aspect=DEBUG

# Root logger (optional)
logging.level.root=INFO

# Console log format
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
