spring.application.name=chatbot
server.port=8087
openai.api.key=sk-zNjCgLYu6OPGZ-RPA2cFvt4eUhVzQYT6gY4AtSbCUtT3BlbkFJk019hHVXtLN-ZDnJn599W_OcQGP0LitFURLNkhxOAA
eureka.client.service-url.defaultZone=http://localhost:8080/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
logging.level.com.cropdeal.chatbot=INFO
logging.level.com.cropdeal.chatbot.controller=DEBUG
logging.level.com.cropdeal.chatbot.service=DEBUG
logging.level.com.cropdeal.chatbot.aspect=DEBUG

logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
